version: "3.8"

services:
  nextjs:
    build: .
    container_name: mileagebuddy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./out:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - nextjs
