// README
// This is (obviously) a list of dummy Vehicles for testing purposes. It is used in the fake redux store in my unit tests.

import { Vehicle } from "../server/types/VehicleTypes/GetVehicleTypes";

const testVehicles: Vehicle[] = [
	// Gas Vehicle 1
	{
		id: 10,
		userid: "b1b2b3b4-1234-5678-9abc-def012345678",
		vehiclesOrder: 1,
		type: "gas",
		vehicleData: {
			vehicleID: 10,
			vehicleName: "Ford F-150",
			year: 2018,
			make: "Ford",
			model: "F-150",
			trim: "XLT",
			highwayMPG: 20,
		},
		purchaseAndSales: {
			vehicleID: 10,
			yearPurchased: 2018,
			purchasePrice: 30000,
			downPaymentAmount: 5000,
			willSellCarAfterYears: 7,
			milesBoughtAt: 15000,
			willSellCarAtMiles: 150000,
			willSellCarAtPrice: 15000,
		},
		usage: {
			vehicleID: 10,
			averageDailyMiles: 50,
			weeksPerYear: 50,
			percentHighway: 60,
			extraDistanceMiles: 10,
			extraDistancePercentHighway: 70,
		},
		fixedCosts: {
			vehicleID: 10,
			yearlyInsuranceCost: 1200,
			yearlyRegistrationCost: 150,
			yearlyTaxes: 250,
			monthlyLoanPayment: 350,
			monthlyWarrantyCost: 50,
			inspectionCost: 100,
			otherYearlyCosts: 200,
		},
		yearlyMaintenanceCosts: {
			vehicleID: 10,
			oilChanges: 150,
			tires: 400,
			batteries: 0,
			brakes: 300,
			other: 100,
		},
		variableCosts: {
			vehicleID: 10,
			monthlyParkingCosts: 0,
			monthlyTolls: 20,
			monthlyCarWashCost: 15,
			monthlyMiscellaneousCosts: 40,
			monthlyCostDeductions: 0,
		},
		gasVehicleData: {
			vehicleID: 10,
			gasCostPerGallon: 3.5,
			milesPerGallonHighway: 20,
			milesPerGallonCity: 15,
		},
	},

	// Gas Vehicle 2
	{
		id: 102,
		userid: "c2c3c4c5-2345-6789-abcd-ef0123456789",
		vehiclesOrder: 2,
		type: "gas",
		vehicleData: {
			vehicleID: 102,
			vehicleName: "Toyota Camry",
			year: 2020,
			make: "Toyota",
			model: "Camry",
			trim: "SE",
			highwayMPG: 32,
		},
		purchaseAndSales: {
			vehicleID: 102,
			yearPurchased: 2020,
			purchasePrice: 25000,
			downPaymentAmount: 3000,
			willSellCarAfterYears: 5,
			milesBoughtAt: 12000,
			willSellCarAtMiles: 120000,
			willSellCarAtPrice: 10000,
		},
		usage: {
			vehicleID: 102,
			averageDailyMiles: 30,
			weeksPerYear: 48,
			percentHighway: 50,
			extraDistanceMiles: 5,
			extraDistancePercentHighway: 60,
		},
		fixedCosts: {
			vehicleID: 102,
			yearlyInsuranceCost: 1000,
			yearlyRegistrationCost: 180,
			yearlyTaxes: 220,
			monthlyLoanPayment: 300,
			monthlyWarrantyCost: 40,
			inspectionCost: 80,
			otherYearlyCosts: 150,
		},
		yearlyMaintenanceCosts: {
			vehicleID: 102,
			oilChanges: 120,
			tires: 350,
			batteries: 0,
			brakes: 250,
			other: 120,
		},
		variableCosts: {
			vehicleID: 102,
			monthlyParkingCosts: 0,
			monthlyTolls: 10,
			monthlyCarWashCost: 20,
			monthlyMiscellaneousCosts: 30,
			monthlyCostDeductions: 0,
		},
		gasVehicleData: {
			vehicleID: 102,
			gasCostPerGallon: 3.6,
			milesPerGallonHighway: 32,
			milesPerGallonCity: 24,
		},
	},

	// Electric Vehicle 1
	{
		id: 201,
		userid: "d3d4d5d6-3456-789a-bcde-f123456789ab",
		vehiclesOrder: 3,
		type: "electric",
		vehicleData: {
			vehicleID: 201,
			vehicleName: "Tesla Model 3",
			year: 2021,
			make: "Tesla",
			model: "Model 3",
			trim: "Long Range",
			highwayMPG: 130, // Approximate MPGe for highways
		},
		purchaseAndSales: {
			vehicleID: 201,
			yearPurchased: 2021,
			purchasePrice: 45000,
			downPaymentAmount: 5000,
			willSellCarAfterYears: 6,
			milesBoughtAt: 8000,
			willSellCarAtMiles: 100000,
			willSellCarAtPrice: 20000,
		},
		usage: {
			vehicleID: 201,
			averageDailyMiles: 40,
			weeksPerYear: 50,
			percentHighway: 65,
			extraDistanceMiles: 10,
			extraDistancePercentHighway: 70,
		},
		fixedCosts: {
			vehicleID: 201,
			yearlyInsuranceCost: 1100,
			yearlyRegistrationCost: 100,
			yearlyTaxes: 300,
			monthlyLoanPayment: 450,
			monthlyWarrantyCost: 30,
			inspectionCost: 0,
			otherYearlyCosts: 180,
		},
		yearlyMaintenanceCosts: {
			vehicleID: 201,
			oilChanges: 0,
			tires: 300,
			batteries: 0,
			brakes: 200,
			other: 100,
		},
		variableCosts: {
			vehicleID: 201,
			monthlyParkingCosts: 25,
			monthlyTolls: 15,
			monthlyCarWashCost: 0,
			monthlyMiscellaneousCosts: 50,
			monthlyCostDeductions: 0,
		},
		electricVehicleData: {
			vehicleID: 201,
			costPerCharge: 15,
			milesPerCharge: 300,
		},
	},

	// Electric Vehicle 2
	{
		id: 202,
		userid: "e4e5e6e7-4567-89ab-cdef-23456789abcd",
		vehiclesOrder: 4,
		type: "electric",
		vehicleData: {
			vehicleID: 202,
			vehicleName: "Nissan Leaf",
			year: 2019,
			make: "Nissan",
			model: "Leaf",
			trim: "SV",
			highwayMPG: 100, // Approximate MPGe for highways
		},
		purchaseAndSales: {
			vehicleID: 202,
			yearPurchased: 2019,
			purchasePrice: 30000,
			downPaymentAmount: 4000,
			willSellCarAfterYears: 5,
			milesBoughtAt: 10000,
			willSellCarAtMiles: 80000,
			willSellCarAtPrice: 12000,
		},
		usage: {
			vehicleID: 202,
			averageDailyMiles: 35,
			weeksPerYear: 52,
			percentHighway: 55,
			extraDistanceMiles: 7,
			extraDistancePercentHighway: 65,
		},
		fixedCosts: {
			vehicleID: 202,
			yearlyInsuranceCost: 950,
			yearlyRegistrationCost: 130,
			yearlyTaxes: 210,
			monthlyLoanPayment: 320,
			monthlyWarrantyCost: 35,
			inspectionCost: 90,
			otherYearlyCosts: 160,
		},
		yearlyMaintenanceCosts: {
			vehicleID: 202,
			oilChanges: 0,
			tires: 280,
			batteries: 0,
			brakes: 220,
			other: 110,
		},
		variableCosts: {
			vehicleID: 202,
			monthlyParkingCosts: 20,
			monthlyTolls: 12,
			monthlyCarWashCost: 0,
			monthlyMiscellaneousCosts: 35,
			monthlyCostDeductions: 0,
		},
		electricVehicleData: {
			vehicleID: 202,
			milesPerCharge: 250,
			costPerCharge: 10,
		},
	},

	// Hybrid Vehicle 1 (Plugin Hybrid)
	{
		id: 301,
		userid: "f5f6f7f8-5678-9abc-def0-1234567890ab",
		vehiclesOrder: 5,
		type: "hybrid",
		vehicleData: {
			vehicleID: 301,
			vehicleName: "Toyota Prius Prime",
			year: 2022,
			make: "Toyota",
			model: "Prius Prime",
			trim: "XLE",
			highwayMPG: 54,
		},
		purchaseAndSales: {
			vehicleID: 301,
			yearPurchased: 2022,
			purchasePrice: 32000,
			downPaymentAmount: 4500,
			willSellCarAfterYears: 7,
			milesBoughtAt: 5000,
			willSellCarAtMiles: 110000,
			willSellCarAtPrice: 11000,
		},
		usage: {
			vehicleID: 301,
			averageDailyMiles: 35,
			weeksPerYear: 51,
			percentHighway: 45,
			extraDistanceMiles: 8,
			extraDistancePercentHighway: 60,
		},
		fixedCosts: {
			vehicleID: 301,
			yearlyInsuranceCost: 1050,
			yearlyRegistrationCost: 120,
			yearlyTaxes: 180,
			monthlyLoanPayment: 380,
			monthlyWarrantyCost: 25,
			inspectionCost: 85,
			otherYearlyCosts: 140,
		},
		yearlyMaintenanceCosts: {
			vehicleID: 301,
			oilChanges: 80,
			tires: 320,
			batteries: 50,
			brakes: 180,
			other: 140,
		},
		variableCosts: {
			vehicleID: 301,
			monthlyParkingCosts: 15,
			monthlyTolls: 18,
			monthlyCarWashCost: 25,
			monthlyMiscellaneousCosts: 40,
			monthlyCostDeductions: 10,
		},
		hybridVehicleData: {
			vehicleID: 301,
			gasCostPerGallon: 3.4,
			milesPerGallonHighway: 55,
			milesPerGallonCity: 53,
			electricityCostPerKWh: 0.15,
			milesPerKWhHighway: 4.0,
			milesPerKWhCity: 4.5,
			percentElectricDriving: 60,
		},
	},

	// Hybrid Vehicle 2 (Plugin Hybrid)
	{
		id: 302,
		userid: "g6g7g8g9-6789-abcd-ef01-234567890abc",
		vehiclesOrder: 6,
		type: "hybrid",
		vehicleData: {
			vehicleID: 302,
			vehicleName: "Hyundai Ioniq Plug-in",
			year: 2021,
			make: "Hyundai",
			model: "Ioniq",
			trim: "Limited",
			highwayMPG: 52,
		},
		purchaseAndSales: {
			vehicleID: 302,
			yearPurchased: 2021,
			purchasePrice: 28000,
			downPaymentAmount: 3800,
			willSellCarAfterYears: 6,
			milesBoughtAt: 6000,
			willSellCarAtMiles: 95000,
			willSellCarAtPrice: 9500,
		},
		usage: {
			vehicleID: 302,
			averageDailyMiles: 42,
			weeksPerYear: 49,
			percentHighway: 60,
			extraDistanceMiles: 12,
			extraDistancePercentHighway: 75,
		},
		fixedCosts: {
			vehicleID: 302,
			yearlyInsuranceCost: 980,
			yearlyRegistrationCost: 140,
			yearlyTaxes: 160,
			monthlyLoanPayment: 340,
			monthlyWarrantyCost: 35,
			inspectionCost: 75,
			otherYearlyCosts: 130,
		},
		yearlyMaintenanceCosts: {
			vehicleID: 302,
			oilChanges: 90,
			tires: 300,
			batteries: 60,
			brakes: 190,
			other: 120,
		},
		variableCosts: {
			vehicleID: 302,
			monthlyParkingCosts: 10,
			monthlyTolls: 22,
			monthlyCarWashCost: 15,
			monthlyMiscellaneousCosts: 30,
			monthlyCostDeductions: 15,
		},
		hybridVehicleData: {
			vehicleID: 302,
			gasCostPerGallon: 3.45,
			milesPerGallonHighway: 59,
			milesPerGallonCity: 57,
			electricityCostPerKWh: 0.14,
			milesPerKWhHighway: 4.2,
			milesPerKWhCity: 4.7,
			percentElectricDriving: 55,
		},
	},
];

export default testVehicles;
