import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import { ThemeWrapper } from "../../providers";
import { Header } from "@/components/Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// added suppressHydrationWarning because of darkmode stuff
		// The mismatch between the server and client side rendered content for dark mode is resolved by our ThemeWrapper, not to worry
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* ThemeWrapper is the dark/light theme wrapper */}
				<ThemeWrapper>
					<StoreProvider>
						<Header />
						{children}
					</StoreProvider>
				</ThemeWrapper>
			</body>
		</html>
	);
}
